export const birthdayEvents = [
  { name: "Liz Clark", date: "2026-04-13", displayDate: "April 13", photo: "liz-clark.webp", sourceNote: "Liz Clark.md" },
  { name: "Ed Ouyang", date: "2026-05-02", displayDate: "May 2", photo: "ed-ouyang.webp", sourceNote: "Ed Ouyang.md" },
  { name: "Kirsten Regalia", date: "2026-06-04", displayDate: "June 4", photo: "kirsten-regalia.webp", sourceNote: "Kirsten Regalia.md" },
  { name: "Patrick McKenzie", date: "2026-06-13", displayDate: "June 13", photo: "patrick-mckenzie.webp", sourceNote: "Patrick McKenzie.md" },
  { name: "Maureen Morgan", date: "2026-07-30", displayDate: "July 30", photo: "maureen-morgan.webp", sourceNote: "Maureen Morgan.md" },
  { name: "Suk Seo", date: "2026-08-28", displayDate: "August 28", photo: "suk-seo.webp", sourceNote: "Suk Seo.md" },
  { name: "Arun Suryaprasad", date: "2026-08-29", displayDate: "August 29", photo: "arun-suryaprasad.webp", sourceNote: "Arun Suryaprasad.md" },
  { name: "Mariel Bailey", date: "2026-08-31", displayDate: "August 31", photo: "mariel-bailey.webp", sourceNote: "Mariel Bailey.md" },
  { name: "Steve Cheng", date: "2026-09-05", displayDate: "September 5", photo: "steve-cheng.webp", sourceNote: "Steve Cheng.md" },
  { name: "Sammy Tesfay", date: "2026-09-07", displayDate: "September 7", photo: "sammy-tesfay.webp", sourceNote: "Sammy Tesfay.md" },
  { name: "Ahilan Arulanandan", date: "2026-09-08", displayDate: "September 8", photo: "ahilan-arulanandan.webp", sourceNote: "Ahilan Arulanandan.md" },
  { name: "Tom Haddad", date: "2026-09-28", displayDate: "September 28", photo: "tom-haddad.webp", sourceNote: "Tom Haddad.md" },
  { name: "Jag Mathur", date: "2026-10-01", displayDate: "October 1", photo: "jag-mathur.webp", sourceNote: "Jag Mathur.md" },
  { name: "Anish Patel", date: "2026-10-14", displayDate: "October 14", photo: "anish-patel.webp", sourceNote: "Anish Patel.md" },
  { name: "Erina Foster", date: "2026-10-17", displayDate: "October 17", photo: "erina-foster.webp", sourceNote: "Erina Foster.md" },
  { name: "Dan Chung", date: "2026-11-16", displayDate: "November 16", photo: "dan-chung.webp", sourceNote: "Dan Chung.md" },
  { name: "Roshan Patel", date: "2026-11-21", displayDate: "November 21", photo: "roshan-patel.webp", source: "user" },
  { name: "Simon Chan", date: "2026-11-29", displayDate: "November 29", photo: "simon-chan.webp", sourceNote: "Simon Chan.md" },
  { name: "Courtney Gonzales", date: "2026-11-30", displayDate: "November 30", photo: "courtney-gonzales.webp", sourceNote: "Courtney Gonzales.md" },
  { name: "T.R. Levin", date: "2026-12-29", displayDate: "December 29", photo: "tr-levin.webp", sourceNote: "T.R. Levin.md" },
];
